sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t docto-ram/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docto-ram/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-123456789"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
